/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboardforsensordata;

/**
 *
 * @author kgl
 */
public class mainApp extends javax.swing.JFrame {

    /**
     * Creates new form mainApp
     */
    public mainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftNav = new javax.swing.JPanel();
        AppName = new javax.swing.JLabel();
        Welcome_userLabe = new javax.swing.JLabel();
        DashboardButton = new rojerusan.RSButtonPane();
        DashboardLabel = new javax.swing.JLabel();
        DataButton = new rojerusan.RSButtonPane();
        DataLabel = new javax.swing.JLabel();
        StatisticsButton = new rojerusan.RSButtonPane();
        StatisticsLabel = new javax.swing.JLabel();
        SettingsButton = new rojerusan.RSButtonPane();
        SettingsLabel = new javax.swing.JLabel();
        ExitButton = new rojerusan.RSButtonPane();
        ExitLabel = new javax.swing.JLabel();
        PresentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftNav.setBackground(new java.awt.Color(23, 23, 69));
        LeftNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AppName.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        AppName.setForeground(new java.awt.Color(254, 254, 254));
        AppName.setText("NodeMCU-DHT11 Dashboard");
        LeftNav.add(AppName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        Welcome_userLabe.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Welcome_userLabe.setForeground(new java.awt.Color(254, 254, 254));
        Welcome_userLabe.setText("Welcome \"Username\"");
        LeftNav.add(Welcome_userLabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 30));

        DashboardButton.setBackground(new java.awt.Color(23, 23, 69));
        DashboardButton.setForeground(new java.awt.Color(254, 254, 254));
        DashboardButton.setColorHover(new java.awt.Color(48, 48, 145));
        DashboardButton.setColorNormal(new java.awt.Color(23, 23, 69));

        DashboardLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        DashboardLabel.setForeground(new java.awt.Color(254, 254, 254));
        DashboardLabel.setText("Dashboard");

        javax.swing.GroupLayout DashboardButtonLayout = new javax.swing.GroupLayout(DashboardButton);
        DashboardButton.setLayout(DashboardButtonLayout);
        DashboardButtonLayout.setHorizontalGroup(
            DashboardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardButtonLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(DashboardLabel)
                .addGap(52, 52, 52))
        );
        DashboardButtonLayout.setVerticalGroup(
            DashboardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardButtonLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(DashboardLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        LeftNav.add(DashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 80));

        DataButton.setBackground(new java.awt.Color(23, 23, 69));
        DataButton.setColorHover(new java.awt.Color(48, 48, 145));
        DataButton.setColorNormal(new java.awt.Color(23, 23, 69));

        DataLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        DataLabel.setForeground(new java.awt.Color(254, 254, 254));
        DataLabel.setText("Data");

        javax.swing.GroupLayout DataButtonLayout = new javax.swing.GroupLayout(DataButton);
        DataButton.setLayout(DataButtonLayout);
        DataButtonLayout.setHorizontalGroup(
            DataButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataButtonLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(DataLabel)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        DataButtonLayout.setVerticalGroup(
            DataButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataButtonLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(DataLabel)
                .addGap(22, 22, 22))
        );

        LeftNav.add(DataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 80));

        StatisticsButton.setBackground(new java.awt.Color(23, 23, 69));
        StatisticsButton.setColorHover(new java.awt.Color(48, 48, 145));
        StatisticsButton.setColorNormal(new java.awt.Color(23, 23, 69));

        StatisticsLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        StatisticsLabel.setForeground(new java.awt.Color(254, 254, 254));
        StatisticsLabel.setText("Statistics");

        javax.swing.GroupLayout StatisticsButtonLayout = new javax.swing.GroupLayout(StatisticsButton);
        StatisticsButton.setLayout(StatisticsButtonLayout);
        StatisticsButtonLayout.setHorizontalGroup(
            StatisticsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatisticsButtonLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(StatisticsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        StatisticsButtonLayout.setVerticalGroup(
            StatisticsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatisticsButtonLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(StatisticsLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        LeftNav.add(StatisticsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 80));

        SettingsButton.setBackground(new java.awt.Color(23, 23, 69));
        SettingsButton.setColorHover(new java.awt.Color(48, 48, 145));
        SettingsButton.setColorNormal(new java.awt.Color(23, 23, 69));

        SettingsLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        SettingsLabel.setForeground(new java.awt.Color(254, 254, 254));
        SettingsLabel.setText("Settings");

        javax.swing.GroupLayout SettingsButtonLayout = new javax.swing.GroupLayout(SettingsButton);
        SettingsButton.setLayout(SettingsButtonLayout);
        SettingsButtonLayout.setHorizontalGroup(
            SettingsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsButtonLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(SettingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        SettingsButtonLayout.setVerticalGroup(
            SettingsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsButtonLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SettingsLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        LeftNav.add(SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, 80));

        ExitButton.setBackground(new java.awt.Color(23, 23, 69));
        ExitButton.setColorHover(new java.awt.Color(48, 48, 145));
        ExitButton.setColorNormal(new java.awt.Color(23, 23, 69));

        ExitLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ExitLabel.setForeground(new java.awt.Color(254, 254, 254));
        ExitLabel.setText("Exit");

        javax.swing.GroupLayout ExitButtonLayout = new javax.swing.GroupLayout(ExitButton);
        ExitButton.setLayout(ExitButtonLayout);
        ExitButtonLayout.setHorizontalGroup(
            ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitButtonLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(ExitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        ExitButtonLayout.setVerticalGroup(
            ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitButtonLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ExitLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        LeftNav.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 230, 80));

        getContentPane().add(LeftNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 900));

        PresentPanel.setBackground(new java.awt.Color(254, 254, 254));
        PresentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PresentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1370, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppName;
    private rojerusan.RSButtonPane DashboardButton;
    private javax.swing.JLabel DashboardLabel;
    private rojerusan.RSButtonPane DataButton;
    private javax.swing.JLabel DataLabel;
    private rojerusan.RSButtonPane ExitButton;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JPanel LeftNav;
    private javax.swing.JPanel PresentPanel;
    private rojerusan.RSButtonPane SettingsButton;
    private javax.swing.JLabel SettingsLabel;
    private rojerusan.RSButtonPane StatisticsButton;
    private javax.swing.JLabel StatisticsLabel;
    private javax.swing.JLabel Welcome_userLabe;
    // End of variables declaration//GEN-END:variables
}
